package com.exciting.dao.mapper;

import com.exciting.dao.entity.po.Exciting;

import java.util.List;

public interface ExcitingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    int insert(Exciting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    int insertSelective(Exciting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    Exciting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Exciting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exciting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Exciting record);

    List<Exciting> listByExciting(Exciting record);
}